spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/lugaritmo_db}
    username: ${DB_USER}
    password: ${DB_PASS:tu_password_local}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect